// IMPORT INQUIRE PACKAGE
// IMPORT THE SQL2 PACKAGE???? MAYBE JUST FOR INDEX PAGE
// IMPORT THE CONSOLE TABLE PACKAGE TO SHOW THE TABLES OF DATA NEATLY IN THE CONSOLE

// IMPORT THE ASCii-ART LOGO THING FOR THE INTRO -- CAN DO LAST

// MAyBE NEED TO IMPORT THE API FILE TO HERE TO CONNECT THE FETCH WITH THE API RECIEVE WITH EXPRESS????? DOUBLE CHECK ALLL THAT

// WRITE UP THE INQUIRE PROMPTS AND MAKE IT SO THAT IF THEY WANT TO QUIT IT CANCELS OR IF THEY WANT TO SELECT THE PROMPTS THEN IT GOES TO THOSE OTHER PROMPTS

// MAKE THE INQUIRE RESPONSES CALL THE CLASS IF ITS CREATING AND CREATE NEW CLASS TO THEN CALL A PUT FETCH REQUEST WITH THE NEW CLASS AS THE BODY


// CREATE THE FETCH CALLS FOR THE PROMPT ANSWERS THAT ARE JYUST WANTING INFOR AND ADD IN THE PATHS FOR THE API GET REQUEST

// CREATE FETCH CALLS FOR THE DELTETE OR MAYBE UPDATE IF THEY WANT THAT WITH THE INQUIRE RESPONSEES AND THEN FOR THE API CALL 