// IMPPORT EXPRESS 
// IMPORT MYSQL- LOOK AT THE MINI PROJET FOR THAT STUFF
// IMPORT THE ROUTER FROM THE ROUTES FOLDER WITH WHATEVER ROUTE NEEDED
// ADD IN THE PORT WITH THE ENV.process PORT ONE OR 3001

// DO app.useJSON AND URL ENCODED

// CREATE CONNEcTION FOR SQL

// MAKE THE PATHS FOR THE REQUIRED ONES AND THEN MAYBE HAVE TO USE A ROUTER IF NEED BE

// WRITE IN THE GET/POST/DELTE/PUT etc AND ADD IN THE SQL QUERIES AS WELL

// ADD IN THE LISTENER